restricted-packages: Add gpg support for file integrity checking

diff --git a/client/restricted-packages/lib/helpers/download b/client/restricted-packages/lib/helpers/download
--- a/client/restricted-packages/lib/helpers/download
+++ b/client/restricted-packages/lib/helpers/download
@@ -56,7 +56,9 @@ mkdir -p "/state/restricted-packages/${package}/${upstream_pack_md5sum}"
 trap on_exit EXIT
 
 if [ -x "${custom_script}" ]; then
-    "${custom_script}" "${url_file}" "${upstream_pack}.tmp"
+    "${custom_script}" "${url_file}" "${upstream_pack}.tmp" || {
+      echo "E: package downloader returned an error!"; exit 1;
+    }
 else
     wget \
         --no-use-server-timestamps \
@@ -67,11 +69,13 @@ else
         --output-document "${upstream_pack}.tmp"
 fi
 
-echo "${upstream_pack_md5sum}  ${upstream_pack}.tmp" \
-    | md5sum --check --status 2>/dev/null || {
-    echo "E: downloaded upstream pack has incorrect checksum" >&2
-    exit 1
-}
+if [ ! -f "${upstream_pack_md5sum}.nocheck" ]; then
+  echo "${upstream_pack_md5sum}  ${upstream_pack}.tmp" \
+      | md5sum --check --status 2>/dev/null || {
+      echo "E: downloaded upstream pack has incorrect checksum" >&2
+      exit 1
+  }
+fi
 
 mv "${upstream_pack}.tmp" "${upstream_pack}"
 
